version: "3"

services:
  api:
    build: planner/models
    image: event-planner-api:latest
    ports:
      - "7000:7000"
    env_file:
      - .env.prod

  database:
    image: mongo:5.0.15
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data: